### ISSUE TITLE
Migrate to Liquidsoap 2.0

### ISSUE THREAD

**Issue by gammaw** [lahmacunradio/liquidsoap#422]
Sources (documentation): 
https://www.liquidsoap.info/doc-dev/reference.html
https://github.com/savonet/book/raw/main/book.pdf

Main features (validated via [test config](https://github.com/mmmnmnm/lahmacun/blob/%23422-liquidsoap-2.0.0/azuracast/test/liquidsoap_custom_delay_example.liq)):
- [x] **Fading** -> Done per https://github.com/mmmnmnm/lahmacun/commit/42f74d960810ffca1994b227a2c9ebf3094c92dc 
- [x] **~~Skipping~~** -> there's a way https://github.com/savonet/liquidsoap/discussions/2123 but tricky and we may not need it that badly
- [x] **Live source** (check with fading too, see https://github.com/mmmnmnm/lahmacun/issues/459)
- [x] **Show scheduling** w/ the `delay` operator (stable in tests, see [here](https://github.com/mmmnmnm/lahmacun/blob/%23422-liquidsoap-2.0.0/azuracast/test/liquidsoap_custom_delay_example.liq))
- [x] **Jingle on show start**, see https://github.com/mmmnmnm/lahmacun/issues/449
- [x] **External relay**, see https://github.com/mmmnmnm/lahmacun/issues/340, NEW: https://github.com/savonet/liquidsoap/discussions/2058
- [x] AC 0.17.3 uses `cue_cut` to prepare playlists. Why? If reasonable, use it (instead of `audio_to_stereo`) -> Discord
- [x] ~~Skip off air track when returning from show~~
- [x] Check `playlist` parameter's for consistency

**Comment by gammaw** [comment]
Suddenly we cannot build the latest Liquidsoap version (2.0.0-beta2), we posted for help https://github.com/savonet/liquidsoap/issues/1693#issuecomment-874314352

**Comment by gammaw** [comment]
It turns out (see https://github.com/savonet/liquidsoap/issues/1728#issuecomment-877713059) that the installation of beta2 works, the original issue has rather to do with https://github.com/mmmnmnm/lahmacun/issues/424, and it's fixed (hopefully) by this commit e72a26cf307cac8810c78b96706be23c480c1a11.

**Comment by gammaw** [comment]
Update: no syntactical error after last commit, but we're currently seeing a runtime error I cannot yet explain -> see https://github.com/savonet/liquidsoap/issues/1732

**Comment by gammaw** [comment]
Checklist:
- [ ] If the Liquidsoap version has changed, check if it runs on the dev server. 
- [ ] Live show works. 
- [ ] Shows start on time. 
- [ ] Fade in/out work. 
- [ ] Jingles play. 
- [ ] Off air plays. 
- [ ] Ambient off air plays. 
- [ ] Player works (ideally for all types of playlists/live). 

We can later move the checklist to a Wiki page or something.

**Comment by gammaw** [comment]
A current issue: I see such entries in the LS log but only via the Azuracast setup (not in the local/standalone LS container). Note: all playlists are defined in Azuracast and radio still outputs something (LS config can start). Will look into it later. 

```
2021/08/12 15:50:59 [playlist.basic:3] Wrong mime type application/x-empty for playlist!
2021/08/12 15:50:59 [playlist parser:3] No format found
```

**Comment by gammaw** [comment]
It turns out that it was due to empty playlists but because of the log level (3) Liquidsoap didn't print the playlist name along with the error (not the best logging logic ...). A similar error message (`Wrong mime type application/csv for playlist!`) was thrown for the `OFF AIR` playlist, possibly due to some files in the playlist the LS doesn't like, I managed to find two okay files and now  we don't have any warning or error (dev server), which is good :) 

I'll continue with the checklist above.

**Comment by gammaw** [comment]
Status: LS 2.0.1 has been released, fading still doesn't work. Details in the issue above and in the LS Slack help channel.

**Comment by gammaw** [comment]
Good news: there is fading! :) New related issue: https://github.com/savonet/liquidsoap/issues/2124

**Comment by gammaw** [comment]
Status: after a eureka effect of how transitions and **fading** in a switch work (and not work)( (details see here: https://github.com/savonet/liquidsoap/issues/2124) it seems that the current fading solution (which will be a pradigm shift in our Liquidsoap logic) seems to work nicely. Next up: check **skipping** tracks (hint: https://github.com/savonet/liquidsoap/discussions/2123#discussioncomment-1870488), if we want to keep the behavior as we have it know (currently we skip OFF AIR tracks when a scheduled show comes in, see https://github.com/mmmnmnm/lahmacun/blob/eee252efe8166a949ac3d34df7b9f1cef632b0e6/azuracast/liquidsoap_custom.liq#L327).
